- hosts: grafana
  remote_user: stanislav
  become: yes
  become_method: sudo
  vars:
    prometheus_ip: "{{ groups['prometheus'] | map('extract', hostvars, ['inventory_hostname']) | join ('') }}"
    grafana_ip: "{{ groups['grafana'] | map('extract', hostvars, ['inventory_hostname']) | join ('') }}"
  roles:
    - grafana
