---  
- name: restart prometheus   
  service:
    name: prometheus
    state: restarted

- name: prometheus systemd
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: prometheus
